name: 02 - Workflow-events.yaml

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
            run: |
                echo "Event name: ${{ github.event_name }}"